# fly.toml app configuration file generated for gosu-helper on 2024-01-26T22:47:08-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gosu-helper'
primary_region = 'iad'

[build]

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
